# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

language: cpp

compiler:
  - gcc

before_install:
  - export CC=cl
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
# We need wine1.4 to be able to run nmake.exe. wine1.6 or 1.7 does not work
  - sudo apt-get install wine1.4 wget p7zip-full cabextract unzip
  - wget "http://go.microsoft.com/fwlink/?LinkId=104679" -O VC.iso
  - mkdir /tmp/vc
  - 7z x VC.iso -o/tmp/vc
  - cabextract /tmp/vc/VCExpress/Ixpvc.exe -d /tmp/vc/VCExpress
  - wine msiexec /i /tmp/vc/VCExpress/vs_setup.msi  VSEXTUI=1 ADDLOCAL=ALL REBOOT=ReallySuppress /qn
  - wget http://download.microsoft.com/download/a/5/f/a5f0d781-e201-4ab6-8c6a-9bb4efed1e1a/PSDK-SDK_Core_BLD-common.0.cab
  - wget http://download.microsoft.com/download/a/5/f/a5f0d781-e201-4ab6-8c6a-9bb4efed1e1a/PSDK-SDK_Core_BLD-common.1.cab
  - wget http://download.microsoft.com/download/a/5/f/a5f0d781-e201-4ab6-8c6a-9bb4efed1e1a/PSDK-SDK_Core_BLD-common.2.cab
  - wget http://download.microsoft.com/download/a/5/f/a5f0d781-e201-4ab6-8c6a-9bb4efed1e1a/PSDK-SDK_Core_BLD_X86-common.0.cab
  - wget http://download.microsoft.com/download/a/5/f/a5f0d781-e201-4ab6-8c6a-9bb4efed1e1a/PSDK-SDK_Core_BIN-x86.0.cab
  - wget http://download.microsoft.com/download/a/5/f/a5f0d781-e201-4ab6-8c6a-9bb4efed1e1a/PSDK-SDK_MDAC_BLD_X86-common.0.cab
  - wget http://download.microsoft.com/download/a/5/f/a5f0d781-e201-4ab6-8c6a-9bb4efed1e1a/PSDK-SDK_MDAC_BLD-common.0.cab
  - wget "http://www.gisinternals.com/sdk/Download.aspx?file=release-1500-dev.zip" -O /tmp/release-1500-dev.zip
  - unzip /tmp/release-1500-dev.zip release-1500/* -d ~/.wine/drive_c
  - mkdir tmp
  - cabextract -dtmp *.cab
  - for i in tmp/*; do mv $i `echo $i | sed "s/\(.*\)\..*/\1/" | sed "s/\(.*\)_\(.*\)/\1\.\2/"`; done
  - mkdir ~/.wine/drive_c/psdk
  - mv tmp/* ~/.wine/drive_c/psdk
#  - find ~/.wine/drive_c
  - git clone --depth=50 --branch=trunk git://github.com/rouault/gdal.git gdal
  - mv gdal ~/.wine/drive_c
  - cp build.bat /tmp
  - cp build.patch /tmp
  - cp nmake.local ~/.wine/drive_c/gdal/gdal
  - cd ~/.wine/drive_c/gdal/gdal
  - cd frmts/jpeg/libjpeg12
  - cp ../libjpeg/*.h .
  - cp jmorecfg.h.12 jmorecfg.h
  - cp ../libjpeg/*.c .
  - mv jcapimin.c jcapimin12.c
  - mv jcapistd.c jcapistd12.c
  - mv jccoefct.c jccoefct12.c
  - mv jccolor.c jccolor12.c
  - mv jcdctmgr.c jcdctmgr12.c
  - mv jchuff.c jchuff12.c
  - mv jcinit.c jcinit12.c
  - mv jcmainct.c jcmainct12.c
  - mv jcmarker.c jcmarker12.c
  - mv jcmaster.c jcmaster12.c
  - mv jcomapi.c jcomapi12.c
  - mv jcparam.c jcparam12.c
  - mv jcphuff.c jcphuff12.c
  - mv jcprepct.c jcprepct12.c
  - mv jcsample.c jcsample12.c
  - mv jctrans.c jctrans12.c
  - mv jdapimin.c jdapimin12.c
  - mv jdapistd.c jdapistd12.c
  - mv jdatadst.c jdatadst12.c
  - mv jdatasrc.c jdatasrc12.c
  - mv jdcoefct.c jdcoefct12.c
  - mv jdcolor.c jdcolor12.c
  - mv jddctmgr.c jddctmgr12.c
  - mv jdhuff.c jdhuff12.c
  - mv jdinput.c jdinput12.c
  - mv jdmainct.c jdmainct12.c
  - mv jdmarker.c jdmarker12.c
  - mv jdmaster.c jdmaster12.c
  - mv jdmerge.c jdmerge12.c
  - mv jdphuff.c jdphuff12.c
  - mv jdpostct.c jdpostct12.c
  - mv jdsample.c jdsample12.c
  - mv jdtrans.c jdtrans12.c
  - mv jerror.c jerror12.c
  - mv jfdctflt.c jfdctflt12.c
  - mv jfdctfst.c jfdctfst12.c
  - mv jfdctint.c jfdctint12.c
  - mv jidctflt.c jidctflt12.c
  - mv jidctfst.c jidctfst12.c
  - mv jidctint.c jidctint12.c
  - mv jidctred.c jidctred12.c
  - mv jmemansi.c jmemansi12.c
  - mv jmemmgr.c jmemmgr12.c
  - mv jquant1.c jquant112.c
  - mv jquant2.c jquant212.c
  - mv jutils.c jutils12.c
  - cd ../../..
  - patch -p0 < /tmp/build.patch

install:
  - wine cmd /c /tmp/build.bat

script:
  - echo "yes"

notifications:
#  email:
#    recipients:
#      - gdal-commits@lists.osgeo.org

#  irc:
#    channels:
#      - "irc.freenode.org#gdal"
#    use_notice: true
#    on_success: change

